### ISSUE TITLE
What is the different between the goals of SciMLTutorials.jl and this repo ?

### ISSUE THREAD

**Issue by ivaquero** [SciML/SciMLDocs#74]
Will [SciMLTutorials](https://tutorials.sciml.ai/stable/#SciMLTutorials.jl:-Tutorials-for-Scientific-Machine-Learning-and-Differential-Equations) get integrated in this repo ?

**Comment by ArnoStrouwen** [comment]
They are already here: https://docs.sciml.ai/SciMLTutorialsOutput/stable/
But I think the plan is to modernize them and maybe split them up.

The goal of this package is to have all the documentation in one place,
to make it easier for newer people who don't know which functionality is in which  package.

**Comment by ivaquero** [comment]
Thank you for the explanation. This link is helpful. Yeah, I wish this website can be an encyclopedia of SciML universe, and have all content of `SciMLTutorials` and `SciML Book` included.

**Comment by ChrisRackauckas** [comment]
Yeah now that we have this full website and some new compute resources, we're in the process of restructuring a few things. The real thing is that we want all tutorial to be generated from real code and be notified of any breaks. Previously we couldn't build many of the tutorials on demand simply because we were using the standard CI compute. However, that's no longer the case as we have some large AMDCI machines on the BuildKite, so SciMLSensitivity.jl for example has a 2 1/2 hour doc build. Because of that, sectioning off the building of some of the larger tutorials where they go to rot separately from the package tests is no longer required. And now we have a website to pool it all together, so with that, what do we do next?

With the DiffEq docs we have been changing a bit of how we are focusing the docs now that there is this full SciML docs context. For example, if you look into the deep sections like sensitivity analysis, it just points to the SciMLSensitivity docs now, instead of trying to shove that all into just one page. Because of that, the DiffEq docs can be a lot more "diffeq focused". So now what I want is to have a split in the top level so that there's getting started, domain-specific, and advanced tutorials. These would then trigger on any PR as a downstream test to anything that is DiffEq based, like DiffEqBase (hehe), Sundials, OrdinaryDiffEq, etc. This would mean that SciMLTutorials would be mostly cut up into these tutorials. Some of the highest ones might become part of a showcase that's for the highest level SciMLDocs.jl landing page, i.e. the ones used as an introduction to what SciML is all about.

**Comment by ivaquero** [comment]
Now I better understand the design  of this repo. When I was a very beginner, I needed to spend much extra time on checking API between several different packages, for example, `ModelingToolKit.jl` and `DifferentialEquations.jl` provide similar functions to solve the same problems, so are `DelayDiffEq.jl` and `OrdinaryDiffEq.jl`. I believe this repo can make all the documentation more hierarchically and specifically.

Thanks for all you work.

**Comment by ChrisRackauckas** [comment]
SEe https://github.com/SciML/SciMLDocs/pull/92
